# Generated by Django 4.2.7 on 2023-12-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_customuser_freeword_customuser_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
