# Generated by Django 4.2.7 on 2023-12-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follow_count',
            field=models.IntegerField(default=0, verbose_name='フォロー数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='follower_count',
            field=models.IntegerField(default=0, verbose_name='フォロワー数'),
        ),
    ]
