# Generated by Django 4.2.7 on 2023-12-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='jobs',
        ),
    ]
