# Generated by Django 4.2.7 on 2023-12-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_remove_customuser_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='person',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
