# Generated by Django 4.2.7 on 2023-12-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_customuser_likedposts_post_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
